### ISSUE TITLE
Add responsiveness to the website

### ISSUE THREAD

**Issue by akshita-kamani** [akshita-kamani/Tindog#1]
i want to add responsiveness to the website like while this website open in phone than for ex pricing table should be one in each row

**Comment by imkks** [comment]
I want to work on this issue. Please assign it to me

**Comment by imkks** [comment]
Please assign this issue to me

**Comment by imkks** [comment]
anyone there? I can work on this issue. Please give it to me, I have commented first

**Comment by imkks** [comment]
Thanks
